ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - init: cd open-easyrtc && npm install
  - init: cd open-easyrtc/server_example && npm install
    command: cd open-easyrtc/server_example && npm start
