connectors:
  slack:
    bot-name: agente
    chat-as-user: true
    connect-timeout: 10
    default-room: "#administração-de-redes-de-computadores"
    icon-emoji: ":supervillain:"
    token: $SLACK_TOKEN
logging:
  console: true
  level: debug
parsers:
  crontab:
    enabled: true
  regex:
    enabled: true
skills:
  - name: hi
    path: skills/hi/
welcome-message: true
